### ISSUE TITLE
JPowerShell support for PowerShell on Linux

### ISSUE THREAD

**Issue by DarkLite1** [profesorfalken/jPowerShell#20]
Hi there, frist of all I have to say that I think this is great project. So thank you for putting in the effort in making these classes. 
In [PowerShell.java](https://github.com/profesorfalken/jPowerShell/blob/master/src/main/java/com/profesorfalken/jpowershell/PowerShell.java) on line 110 it states **powershell.exe**.  I think this means there is no support for PowerShell on linux, as we don't use powershell.exe but rather powershell.

When trying to run my own code for powershell on Linux I encountered [this issue](http://stackoverflow.com/questions/44087451/running-a-powershell-file-from-java-says-the-file-does-not-have-a-ps1-extensi) that I've posted on StackOverflow. I would love to hear what you think and if you can support linux too.

Thank you for your help.

**Comment by profesorfalken** [comment]
Hi, 

I am a Linux user myself (I do not have Windows installed at home) and I did not know that Powershell existed for Linux! (in fact I cannot figure out what is the purpose of porting it)

Anyway, I will check the project https://github.com/PowerShell/PowerShell and try to make it work with jPowershell.

I will keep you updated.

Thank you for the info

**Comment by DarkLite1** [comment]
Thank you for your feedback ProfesorFalken, in the meantime I've opened a [ticket ](https://github.com/PowerShell/PowerShell/issues/3837)with them just to be sure it's not in the PowerShell version itself.

I have to admit, I use PowerShell at work on Windows systems. But when I develop a Java program, I tend to do that on my laptop at home which runs Fedora 25. That's how stumbled upon the opensoure version of PowerShell on GitHub. I think it has a lot of potential going for it when it can be cross platform as it already is.

Thanks for looking into this. I'd rather use your proven class then my own stuff.

**Comment by profesorfalken** [comment]
Hello, 

After a first quick & dirty try, it seems to work very well, at least in my system.

I have pushed to Maven Central a new snapshot version you can use to test your case:

You can download the JAR here: https://oss.sonatype.org/content/repositories/snapshots/com/profesorfalken/jPowerShell/1.9-SNAPSHOT/

Or with Maven: 

    <dependency>
         <groupId>com.profesorfalken</groupId>
         <artifactId>jPowerShell</artifactId>
         <version>1.9-SNAPSHOT</version>
     </dependency>

Good luck!

**Comment by DarkLite1** [comment]
Thank you for the upload to Maven Central. I have to admit I'm pretty new to Java and development so please be patient with me..

I've added the dependency to Maven as following:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>PowerShell</groupId>
    <artifactId>PowerShell</artifactId>
    <version>1.0-SNAPSHOT</version>
    
    <dependencies>
        <dependency>
            <groupId>com.profesorfalken</groupId>
            <artifactId>jPowerShell</artifactId>
            <version>1.9-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>
```
Then I created the following class like illustrated on your GitHub home page:
```
import java.util.HashMap;
import java.util.Map;

public class ScriptExecution {
    public static void main(String[] args) {
        PowerShellResponse response = null;
        try {
            //Creates PowerShell session
            PowerShell powerShell = PowerShell.openSession();
            //Increase timeout to give enough time to the script to finish
            Map<String, String> config = new HashMap<String, String>();
            config.put("maxWait", "80000");

            //Execute script
            response = powerShell.configuration(config).executeScript("./myPath/MyScript.ps1");

            //Print results if the script
            System.out.println("Script output:" + response.getCommandOutput());
        } catch(PowerShellNotAvailableException ex) {
            //Handle error when PowerShell is not available in the system
            //Maybe try in another way?
        } finally {
            //Always close PowerShell session to free resources.
            if (powerShell != null)
                powerShell.close();
        }
    }
}
```
At this pont the IDE, IntelliJ, is still not recognizing the classes. Am I missing something super obvious here? Do I need to do a specific `import xxx` at the top of the class to be able to use the Maven dependency?

**Comment by DarkLite1** [comment]
It's just not available in Maven. Can you check if it's possible for you to import via Maven POM the following dependency you posted:

```
<dependency>
     <groupId>com.profesorfalken</groupId>
     <artifactId>jPowerShell</artifactId>
     <version>1.9-SNAPSHOT</version>
 </dependency>
```

**Comment by profesorfalken** [comment]
Hello, 

In my case, I have no problem. I set the dependency in other project, I perform a mvn install and the dependency is downloaded into the maven repo.

Anyway, you can do it manually if you want. 
Download the artifact from sonatype nexus: https://oss.sonatype.org/#nexus-search;quick~jpowershell
And set it into your MAVEN_REPO_DIR/com/profesorfalken/1.9-SNAPSHOT 

Or simply download the jar and add it to the classpath manually.

Best regards

**Comment by DarkLite1** [comment]
Been on vacation for a while, so sorry for the late reply. Finally got around testing it and with the 1.9-SNAPSHOT it seems to work just fine now. Thank you very much for including this.
